# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data/display_ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1086, 620)
        MainWindow.setMinimumSize(QtCore.QSize(0, 20))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/logo_tds.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("border:none;")
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        MainWindow.setDocumentMode(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(41, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame.setStyleSheet("QFrame#frame{\n"
"background-color: rgb(170, 0, 255);\n"
"border-bottom: 2px solid #39add1;\n"
"\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(50, 33))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.topLogo = QtWidgets.QPushButton(self.frame_3)
        self.topLogo.setMinimumSize(QtCore.QSize(45, 25))
        self.topLogo.setMaximumSize(QtCore.QSize(55, 33))
        self.topLogo.setStyleSheet("")
        self.topLogo.setText("")
        self.topLogo.setIcon(icon)
        self.topLogo.setIconSize(QtCore.QSize(30, 30))
        self.topLogo.setObjectName("topLogo")
        self.horizontalLayout_3.addWidget(self.topLogo)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(2, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.topTitleApp = QtWidgets.QLabel(self.frame_4)
        self.topTitleApp.setMaximumSize(QtCore.QSize(350, 16777215))
        self.topTitleApp.setObjectName("topTitleApp")
        self.verticalLayout_2.addWidget(self.topTitleApp)
        self.topVersionApp = QtWidgets.QLabel(self.frame_4)
        self.topVersionApp.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setKerning(True)
        self.topVersionApp.setFont(font)
        self.topVersionApp.setStyleSheet("\n"
"color: rgb(181, 189, 255)")
        self.topVersionApp.setObjectName("topVersionApp")
        self.verticalLayout_2.addWidget(self.topVersionApp)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setContentsMargins(60, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_showC = QtWidgets.QPushButton(self.frame_5)
        self.btn_showC.setMinimumSize(QtCore.QSize(31, 25))
        self.btn_showC.setMaximumSize(QtCore.QSize(31, 25))
        self.btn_showC.setStyleSheet("QPushButton#btn_showC:hover{\n"
"background-color: rgb(90, 106, 152);\n"
"border:none;\n"
"border-radius:3px;\n"
"}\n"
"QPushButton#btn_showC{\n"
"border:none;\n"
"border-radius:3px;\n"
"}")
        self.btn_showC.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/cil-arrow-bottom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_showC.setIcon(icon1)
        self.btn_showC.setObjectName("btn_showC")
        self.horizontalLayout_2.addWidget(self.btn_showC, 0, QtCore.Qt.AlignLeft)
        self.btn_mini = QtWidgets.QPushButton(self.frame_5)
        self.btn_mini.setMinimumSize(QtCore.QSize(31, 25))
        self.btn_mini.setMaximumSize(QtCore.QSize(31, 25))
        self.btn_mini.setStyleSheet("QPushButton#btn_mini:hover{\n"
"background-color: rgb(90, 106, 152);\n"
"border:none;\n"
"border-radius:3px;\n"
"}\n"
"QPushButton#btn_mini{\n"
"border:none;\n"
"border-radius:3px;\n"
"}")
        self.btn_mini.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/icon_minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_mini.setIcon(icon2)
        self.btn_mini.setObjectName("btn_mini")
        self.horizontalLayout_2.addWidget(self.btn_mini)
        self.btn_max = QtWidgets.QPushButton(self.frame_5)
        self.btn_max.setMinimumSize(QtCore.QSize(31, 25))
        self.btn_max.setMaximumSize(QtCore.QSize(31, 25))
        self.btn_max.setStyleSheet("QPushButton#btn_max:hover{\n"
"background-color: rgb(90, 106, 152);\n"
"border:none;\n"
"border-radius:3px;\n"
"}\n"
"QPushButton#btn_max{\n"
"border:none;\n"
"border-radius:3px;\n"
"}")
        self.btn_max.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/icon_maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_max.setIcon(icon3)
        self.btn_max.setObjectName("btn_max")
        self.horizontalLayout_2.addWidget(self.btn_max)
        self.btn_close = QtWidgets.QPushButton(self.frame_5)
        self.btn_close.setMinimumSize(QtCore.QSize(31, 25))
        self.btn_close.setMaximumSize(QtCore.QSize(31, 25))
        self.btn_close.setStyleSheet("QPushButton#btn_close:hover{\n"
"background-color:#ff79c6;\n"
"border:none;\n"
"border-radius:3px;\n"
"}\n"
"QPushButton#btn_close{\n"
"border:none;\n"
"border-radius:3px;\n"
"}")
        self.btn_close.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/icon_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon4)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_2.addWidget(self.btn_close)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("QFrame#frame_2{\n"
"border-radius:0px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.leftMenu = QtWidgets.QFrame(self.frame_2)
        self.leftMenu.setMaximumSize(QtCore.QSize(150, 16777215))
        self.leftMenu.setStyleSheet("QFrame#leftMenu{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px;\n"
"}")
        self.leftMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenu.setObjectName("leftMenu")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.leftMenu)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.leftMenu)
        self.frame_8.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_18 = QtWidgets.QFrame(self.frame_9)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.btn_menu = QtWidgets.QPushButton(self.frame_18)
        self.btn_menu.setGeometry(QtCore.QRect(0, 10, 150, 40))
        self.btn_menu.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_menu.setMaximumSize(QtCore.QSize(150, 40))
        self.btn_menu.setStyleSheet("QPushButton#btn_menu:hover{\n"
"border:none;\n"
"border-radius:2px;\n"
"    background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu.setIcon(icon5)
        self.btn_menu.setObjectName("btn_menu")
        self.verticalLayout_4.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_9)
        self.frame_19.setMinimumSize(QtCore.QSize(0, 500))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.btn_home = QtWidgets.QPushButton(self.frame_19)
        self.btn_home.setGeometry(QtCore.QRect(0, 0, 150, 50))
        self.btn_home.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_home.setMaximumSize(QtCore.QSize(150, 40))
        self.btn_home.setStyleSheet("\n"
"QPushButton#btn_home:hover{\n"
"border:none;\n"
"border-radius:2px;\n"
"    background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_home.setIcon(icon6)
        self.btn_home.setObjectName("btn_home")
        self.btn_batdau = QtWidgets.QPushButton(self.frame_19)
        self.btn_batdau.setGeometry(QtCore.QRect(0, 40, 150, 50))
        self.btn_batdau.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_batdau.setMaximumSize(QtCore.QSize(150, 40))
        self.btn_batdau.setStyleSheet("QPushButton#btn_batdau:hover{\n"
"border:none;\n"
"border-radius:2px;\n"
"    background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/icons8-play-67.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_batdau.setIcon(icon7)
        self.btn_batdau.setObjectName("btn_batdau")
        self.btn_dunglai = QtWidgets.QPushButton(self.frame_19)
        self.btn_dunglai.setGeometry(QtCore.QRect(0, 80, 150, 50))
        self.btn_dunglai.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_dunglai.setMaximumSize(QtCore.QSize(150, 40))
        self.btn_dunglai.setStyleSheet("\n"
"QPushButton#btn_dunglai:hover{\n"
"border:none;\n"
"border-radius:2px;\n"
"    background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_dunglai.setIcon(icon8)
        self.btn_dunglai.setObjectName("btn_dunglai")
        self.btn_history = QtWidgets.QPushButton(self.frame_19)
        self.btn_history.setGeometry(QtCore.QRect(0, 120, 150, 50))
        self.btn_history.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_history.setMaximumSize(QtCore.QSize(150, 40))
        self.btn_history.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_history.setStyleSheet("QPushButton#btn_history:hover{\n"
"border:none;\n"
"border-radius:2px;\n"
"    background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/img/battery.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_history.setIcon(icon9)
        self.btn_history.setObjectName("btn_history")
        self.btn_cauhinh = QtWidgets.QPushButton(self.frame_19)
        self.btn_cauhinh.setGeometry(QtCore.QRect(0, 160, 150, 50))
        self.btn_cauhinh.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_cauhinh.setMaximumSize(QtCore.QSize(150, 40))
        self.btn_cauhinh.setStyleSheet("QPushButton#btn_cauhinh:hover{\n"
"border:none;\n"
"border-radius:2px;\n"
"    background-color: rgb(221, 221, 221);\n"
"}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/img/increase.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cauhinh.setIcon(icon10)
        self.btn_cauhinh.setObjectName("btn_cauhinh")
        self.btn_add_account = QtWidgets.QPushButton(self.frame_19)
        self.btn_add_account.setGeometry(QtCore.QRect(0, 200, 150, 50))
        self.btn_add_account.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_add_account.setMaximumSize(QtCore.QSize(150, 40))
        self.btn_add_account.setStyleSheet("QPushButton#btn_add_account:hover{\n"
"border:none;\n"
"border-radius:2px;\n"
"    background-color: rgb(221, 221, 221);\n"
"}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/img/icons8-folder-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_account.setIcon(icon11)
        self.btn_add_account.setObjectName("btn_add_account")
        self.btn_show = QtWidgets.QPushButton(self.frame_19)
        self.btn_show.setGeometry(QtCore.QRect(0, 240, 150, 50))
        self.btn_show.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_show.setMaximumSize(QtCore.QSize(150, 40))
        self.btn_show.setStyleSheet("QPushButton#btn_show:hover{\n"
"border:none;\n"
"border-radius:2px;\n"
"    background-color: rgb(221, 221, 221);\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/img/ecologist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_show.setIcon(icon12)
        self.btn_show.setObjectName("btn_show")
        self.btn_update = QtWidgets.QPushButton(self.frame_19)
        self.btn_update.setGeometry(QtCore.QRect(0, 280, 150, 50))
        self.btn_update.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_update.setMaximumSize(QtCore.QSize(150, 40))
        self.btn_update.setStyleSheet("QPushButton#btn_update:hover{\n"
"border:none;\n"
"border-radius:2px;\n"
"    background-color: rgb(221, 221, 221);\n"
"}")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/img/updated_app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_update.setIcon(icon13)
        self.btn_update.setObjectName("btn_update")
        self.verticalLayout_4.addWidget(self.frame_19)
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_setting = QtWidgets.QPushButton(self.frame_10)
        self.btn_setting.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_setting.setMaximumSize(QtCore.QSize(150, 40))
        self.btn_setting.setStyleSheet("\n"
"QPushButton#btn_setting:hover{\n"
"border:none;\n"
"border-radius:2px;\n"
"    background-color: rgb(221, 221, 221);\n"
"}\n"
"QPushButton#btn_setting{\n"
"border:none;\n"
"border-radius:2px;\n"
"    color: rgb(77, 82, 120);\n"
"}\n"
"\n"
"QPushButton#btn_setting:pressed{\n"
"border:none;\n"
"border-radius:2px;\n"
"    color: rgb(77, 82, 120);\n"
"    background-color: rgb(207, 207, 207);\n"
"}")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/img/settings-cog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_setting.setIcon(icon14)
        self.btn_setting.setObjectName("btn_setting")
        self.verticalLayout_5.addWidget(self.btn_setting)
        self.verticalLayout_4.addWidget(self.frame_10, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_3.addWidget(self.frame_9)
        self.horizontalLayout_5.addWidget(self.frame_8)
        self.horizontalLayout_4.addWidget(self.leftMenu)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setStyleSheet("QFrame#frame_7{\n"
"border-radius:0px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_11 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_16 = QtWidgets.QFrame(self.frame_11)
        self.frame_16.setStyleSheet("")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_16)
        self.scrollArea.setStyleSheet("\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgba(255,255,255,255);\n"
"    height: 8px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(69, 179, 157);\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgba(255,255,255,255);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(69, 179, 157);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    \n"
"     height: 15px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"   \n"
"     height: 15px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ComboBox */\n"
"QComboBox{\n"
"    padding: 1px;\n"
"    padding-left: 3px;\n"
"    \n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(255, 255, 255);    \n"
"    background-color: rgb(107, 125, 179);\n"
"    padding: 5px;\n"
"    border-radius:4px;\n"
"    selection-background-color: #788dca;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Sliders */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 5px;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(189, 147, 249);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 5px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(189, 147, 249);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CommandLinkButton */\n"
"QCommandLinkButton {    \n"
"    color: rgb(255, 121, 198);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"QCommandLinkButton:hover {    \n"
"    color: rgb(255, 170, 255);\n"
"    background-color: rgb(44, 49, 60);\n"
"}\n"
"QCommandLinkButton:pressed {    \n"
"    color: rgb(189, 147, 249);\n"
"    background-color: rgb(52, 58, 71);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Button */\n"
"#pagesContainer QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"#pagesContainer QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"#pagesContainer QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 936, 575))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_showC = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_showC.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_showC.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_showC.setStyleSheet("QFrame#frame_showC{\n"
"border-bottom: 1px solid #ffffff;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.frame_showC.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_showC.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_showC.setObjectName("frame_showC")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_showC)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_20 = QtWidgets.QFrame(self.frame_showC)
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_8.addWidget(self.frame_20)
        self.verticalLayout_7.addWidget(self.frame_showC)
        self.frame_17 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_17.setStyleSheet("QFrame#frame_17{\n"
"background-color: rgb(236, 236, 236);\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_17)
        self.stackedWidget.setStyleSheet("QStackWidget#stackedWidget{\n"
"\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_tablewidget = QtWidgets.QWidget()
        self.page_tablewidget.setObjectName("page_tablewidget")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.page_tablewidget)
        self.horizontalLayout_21.setSpacing(15)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.stackedWidget.addWidget(self.page_tablewidget)
        self.page_showPage = QtWidgets.QWidget()
        self.page_showPage.setObjectName("page_showPage")
        self.verticalLayout_58 = QtWidgets.QVBoxLayout(self.page_showPage)
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.frame_13 = QtWidgets.QFrame(self.page_showPage)
        self.frame_13.setStyleSheet("QFrame#frame_13{\n"
"border-radius:10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tablewidget_page = QtWidgets.QTableWidget(self.frame_13)
        self.tablewidget_page.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tablewidget_page.setFont(font)
        self.tablewidget_page.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tablewidget_page.setDragEnabled(False)
        self.tablewidget_page.setAlternatingRowColors(False)
        self.tablewidget_page.setShowGrid(False)
        self.tablewidget_page.setGridStyle(QtCore.Qt.NoPen)
        self.tablewidget_page.setWordWrap(True)
        self.tablewidget_page.setCornerButtonEnabled(True)
        self.tablewidget_page.setRowCount(0)
        self.tablewidget_page.setColumnCount(17)
        self.tablewidget_page.setObjectName("tablewidget_page")
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_page.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_page.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_page.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_page.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_page.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_page.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_page.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_page.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_page.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_page.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_page.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_page.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_page.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_page.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_page.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_page.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_page.setHorizontalHeaderItem(16, item)
        self.tablewidget_page.horizontalHeader().setVisible(True)
        self.tablewidget_page.horizontalHeader().setCascadingSectionResizes(False)
        self.tablewidget_page.horizontalHeader().setHighlightSections(False)
        self.tablewidget_page.horizontalHeader().setMinimumSectionSize(5)
        self.tablewidget_page.horizontalHeader().setSortIndicatorShown(False)
        self.tablewidget_page.horizontalHeader().setStretchLastSection(True)
        self.tablewidget_page.verticalHeader().setVisible(False)
        self.tablewidget_page.verticalHeader().setCascadingSectionResizes(False)
        self.tablewidget_page.verticalHeader().setDefaultSectionSize(20)
        self.tablewidget_page.verticalHeader().setHighlightSections(True)
        self.tablewidget_page.verticalHeader().setMinimumSectionSize(20)
        self.tablewidget_page.verticalHeader().setSortIndicatorShown(False)
        self.tablewidget_page.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_9.addWidget(self.tablewidget_page)
        self.verticalLayout_58.addWidget(self.frame_13)
        self.stackedWidget.addWidget(self.page_showPage)
        self.verticalLayout_10.addWidget(self.stackedWidget)
        self.verticalLayout_7.addWidget(self.frame_17)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_11.addWidget(self.scrollArea)
        self.horizontalLayout_10.addWidget(self.frame_16)
        self.frame_cauhinh = QtWidgets.QFrame(self.frame_11)
        self.frame_cauhinh.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_cauhinh.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_cauhinh.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_cauhinh.setStyleSheet("/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"\n"
"SET APP STYLESHEET - FULL STYLES HERE\n"
"DARK THEME - DRACULA COLOR BASED\n"
"\n"
"///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Tooltip */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(168 , 190, 232);\n"
"    height: 8px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(69, 179, 157);\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(170, 183, 184);\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(170, 183, 184);\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(168 , 190, 232);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(69, 179, 157);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(170, 183, 184);\n"
"     height: 15px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(170, 183, 184);\n"
"     height: 15px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"QScrollArea#scrollArea{\n"
"border:none;\n"
"border-radius:2px;\n"
"}\n"
"QFrame#frame_cauhinh{\n"
"background-color: rgb(255, 255, 255);\n"
"border-left:1px solid #ebebeb;\n"
"}")
        self.frame_cauhinh.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_cauhinh.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_cauhinh.setObjectName("frame_cauhinh")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_cauhinh)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_23 = QtWidgets.QFrame(self.frame_cauhinh)
        self.frame_23.setMinimumSize(QtCore.QSize(0, 51))
        self.frame_23.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_23.setStyleSheet("QFrame#frame_23{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_14.setContentsMargins(10, 0, 0, 25)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_26 = QtWidgets.QFrame(self.frame_23)
        self.frame_26.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_26.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_15.setContentsMargins(0, 15, 30, 0)
        self.horizontalLayout_15.setSpacing(7)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btn_reset = QtWidgets.QPushButton(self.frame_26)
        self.btn_reset.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_reset.setFont(font)
        self.btn_reset.setStyleSheet("QPushButton#btn_reset{\n"
"color: rgb(77, 82, 120);\n"
"border-radius:5px;\n"
"border:1px solid #e5e5e5\n"
"}\n"
"QPushButton#btn_reset:hover{\n"
"color: rgb(77, 82, 120);\n"
"border-radius:5px;\n"
"background-color:rgb(234, 234, 234);\n"
"}")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/img/loop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_reset.setIcon(icon15)
        self.btn_reset.setIconSize(QtCore.QSize(15, 20))
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout_15.addWidget(self.btn_reset)
        self.btn_savecmd = QtWidgets.QPushButton(self.frame_26)
        self.btn_savecmd.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_savecmd.setFont(font)
        self.btn_savecmd.setStyleSheet("\n"
"QPushButton#btn_savecmd{\n"
"color: rgb(77, 82, 120);\n"
"border-radius:5px;\n"
"border:1px solid #e5e5e5\n"
"}\n"
"QPushButton#btn_savecmd:hover{\n"
"color: rgb(77, 82, 120);\n"
"border-radius:5px;\n"
"background-color:rgb(234, 234, 234);\n"
"}")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/img/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_savecmd.setIcon(icon16)
        self.btn_savecmd.setObjectName("btn_savecmd")
        self.horizontalLayout_15.addWidget(self.btn_savecmd)
        self.horizontalLayout_14.addWidget(self.frame_26)
        self.verticalLayout_12.addWidget(self.frame_23)
        self.stackedWidget_setting = QtWidgets.QStackedWidget(self.frame_cauhinh)
        self.stackedWidget_setting.setStyleSheet("\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgba(255,255,255,255);\n"
"    height: 8px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(69, 179, 157);\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(170, 183, 184);\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(170, 183, 184);\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgba(255,255,255,255);\n"
"    width: 5px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(69, 179, 157);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(170, 183, 184);\n"
"     height: 15px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(170, 183, 184);\n"
"     height: 15px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ComboBox */\n"
"QComboBox{\n"
"    background-color: rgb(107, 125, 179);\n"
"    border-radius: 4px;\n"
"    border: 1px solid #ffffff;\n"
"    padding: 1px;\n"
"    padding-left: 3px;\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"QComboBox:hover{\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: #788dca;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(data/display_ui/icons/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(255, 255, 255);    \n"
"    background-color: rgb(107, 125, 179);\n"
"    \n"
"    border-radius:4px;\n"
"    selection-background-color: #788dca;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Sliders */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 5px;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(189, 147, 249);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 5px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(189, 147, 249);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CommandLinkButton */\n"
"QCommandLinkButton {    \n"
"    color: rgb(255, 121, 198);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"QCommandLinkButton:hover {    \n"
"    color: rgb(255, 170, 255);\n"
"    background-color: rgb(44, 49, 60);\n"
"}\n"
"QCommandLinkButton:pressed {    \n"
"    color: rgb(189, 147, 249);\n"
"    background-color: rgb(52, 58, 71);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Button */\n"
"#pagesContainer QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"#pagesContainer QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"#pagesContainer QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.stackedWidget_setting.setObjectName("stackedWidget_setting")
        self.page_cauhinh = QtWidgets.QWidget()
        self.page_cauhinh.setMinimumSize(QtCore.QSize(0, 0))
        self.page_cauhinh.setObjectName("page_cauhinh")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.page_cauhinh)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.frame_6 = QtWidgets.QFrame(self.page_cauhinh)
        self.frame_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_27 = QtWidgets.QFrame(self.frame_6)
        self.frame_27.setGeometry(QtCore.QRect(0, 0, 181, 86))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_24 = QtWidgets.QFrame(self.frame_27)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.frame_24)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: red;")
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.verticalLayout_11.addWidget(self.frame_24)
        self.frame_21 = QtWidgets.QFrame(self.frame_27)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.radioTaphoa = QtWidgets.QRadioButton(self.frame_21)
        self.radioTaphoa.setChecked(True)
        self.radioTaphoa.setObjectName("radioTaphoa")
        self.horizontalLayout_7.addWidget(self.radioTaphoa)
        self.radioFile = QtWidgets.QRadioButton(self.frame_21)
        self.radioFile.setObjectName("radioFile")
        self.horizontalLayout_7.addWidget(self.radioFile)
        self.verticalLayout_11.addWidget(self.frame_21)
        self.frame_28 = QtWidgets.QFrame(self.frame_6)
        self.frame_28.setGeometry(QtCore.QRect(180, 0, 301, 81))
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.token_taphoa = QtWidgets.QLineEdit(self.frame_28)
        self.token_taphoa.setStyleSheet("border: 1px solid black;\n"
"padding-left: 5px;")
        self.token_taphoa.setObjectName("token_taphoa")
        self.verticalLayout_13.addWidget(self.token_taphoa)
        self.token_shop = QtWidgets.QLineEdit(self.frame_28)
        self.token_shop.setStyleSheet("border: 1px solid black;\n"
"padding-left: 5px;")
        self.token_shop.setObjectName("token_shop")
        self.verticalLayout_13.addWidget(self.token_shop)
        self.frame_29 = QtWidgets.QFrame(self.frame_6)
        self.frame_29.setGeometry(QtCore.QRect(10, 90, 471, 241))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.textGmail = QtWidgets.QPlainTextEdit(self.frame_29)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textGmail.setFont(font)
        self.textGmail.setStyleSheet("border: 1px solid black;\n"
"padding-left: 5px;")
        self.textGmail.setObjectName("textGmail")
        self.horizontalLayout_16.addWidget(self.textGmail)
        self.frame_31 = QtWidgets.QFrame(self.frame_6)
        self.frame_31.setGeometry(QtCore.QRect(480, 0, 301, 65))
        self.frame_31.setMinimumSize(QtCore.QSize(0, 65))
        self.frame_31.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_3 = QtWidgets.QLabel(self.frame_31)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: red;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_16.addWidget(self.label_3)
        self.key_captcha = QtWidgets.QLineEdit(self.frame_31)
        self.key_captcha.setStyleSheet("border: 1px solid black;\n"
"padding-left: 5px;")
        self.key_captcha.setObjectName("key_captcha")
        self.verticalLayout_16.addWidget(self.key_captcha)
        self.frame_35 = QtWidgets.QFrame(self.frame_6)
        self.frame_35.setGeometry(QtCore.QRect(480, 70, 301, 55))
        self.frame_35.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_7 = QtWidgets.QLabel(self.frame_35)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: red;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_15.addWidget(self.label_7)
        self.path_image = QtWidgets.QLineEdit(self.frame_35)
        self.path_image.setStyleSheet("border: 1px solid black;\n"
"padding-left: 5px;")
        self.path_image.setObjectName("path_image")
        self.verticalLayout_15.addWidget(self.path_image)
        self.frame_22 = QtWidgets.QFrame(self.frame_6)
        self.frame_22.setGeometry(QtCore.QRect(480, 130, 301, 201))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.label_8 = QtWidgets.QLabel(self.frame_22)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: red;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_22)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.sleep_job = QtWidgets.QSpinBox(self.frame_22)
        self.sleep_job.setGeometry(QtCore.QRect(42, 28, 51, 20))
        self.sleep_job.setMinimumSize(QtCore.QSize(0, 0))
        self.sleep_job.setStyleSheet("border: 0.5px solid black;")
        self.sleep_job.setMaximum(9999)
        self.sleep_job.setObjectName("sleep_job")
        self.label_11 = QtWidgets.QLabel(self.frame_22)
        self.label_11.setGeometry(QtCore.QRect(100, 30, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.job_sleep = QtWidgets.QSpinBox(self.frame_22)
        self.job_sleep.setGeometry(QtCore.QRect(215, 27, 51, 21))
        self.job_sleep.setMinimumSize(QtCore.QSize(0, 0))
        self.job_sleep.setStyleSheet("border: 0.5px solid black;")
        self.job_sleep.setMaximum(9999)
        self.job_sleep.setProperty("value", 100)
        self.job_sleep.setObjectName("job_sleep")
        self.label_12 = QtWidgets.QLabel(self.frame_22)
        self.label_12.setGeometry(QtCore.QRect(270, 30, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.startTime = QtWidgets.QTimeEdit(self.frame_22)
        self.startTime.setGeometry(QtCore.QRect(80, 70, 91, 21))
        self.startTime.setStyleSheet("border: 0.5px solid black;")
        self.startTime.setObjectName("startTime")
        self.endTime = QtWidgets.QTimeEdit(self.frame_22)
        self.endTime.setGeometry(QtCore.QRect(80, 100, 91, 21))
        self.endTime.setStyleSheet("border: 0.5px solid black;")
        self.endTime.setObjectName("endTime")
        self.label_13 = QtWidgets.QLabel(self.frame_22)
        self.label_13.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_22)
        self.label_14.setGeometry(QtCore.QRect(10, 100, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_5 = QtWidgets.QLabel(self.frame_22)
        self.label_5.setGeometry(QtCore.QRect(180, 70, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.delayMin = QtWidgets.QSpinBox(self.frame_22)
        self.delayMin.setGeometry(QtCore.QRect(250, 70, 47, 21))
        self.delayMin.setMinimumSize(QtCore.QSize(0, 0))
        self.delayMin.setStyleSheet("border: 0.5px solid black;")
        self.delayMin.setMaximum(9999)
        self.delayMin.setProperty("value", 5)
        self.delayMin.setObjectName("delayMin")
        self.label_6 = QtWidgets.QLabel(self.frame_22)
        self.label_6.setGeometry(QtCore.QRect(180, 100, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.delayMax = QtWidgets.QSpinBox(self.frame_22)
        self.delayMax.setGeometry(QtCore.QRect(250, 100, 47, 21))
        self.delayMax.setStyleSheet("border: 0.5px solid black;")
        self.delayMax.setMaximum(9999)
        self.delayMax.setProperty("value", 10)
        self.delayMax.setObjectName("delayMax")
        self.label_15 = QtWidgets.QLabel(self.frame_22)
        self.label_15.setGeometry(QtCore.QRect(10, 140, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_22)
        self.label_16.setGeometry(QtCore.QRect(280, 140, 16, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.limitXu = QtWidgets.QLineEdit(self.frame_22)
        self.limitXu.setGeometry(QtCore.QRect(160, 140, 113, 21))
        self.limitXu.setStyleSheet("border: 0.5px solid black;\n"
"padding-left: 4px;")
        self.limitXu.setObjectName("limitXu")
        self.verticalLayout_25.addWidget(self.frame_6)
        self.stackedWidget_setting.addWidget(self.page_cauhinh)
        self.page_add = QtWidgets.QWidget()
        self.page_add.setObjectName("page_add")
        self.verticalLayout_55 = QtWidgets.QVBoxLayout(self.page_add)
        self.verticalLayout_55.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_55.setSpacing(0)
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.frame_25 = QtWidgets.QFrame(self.page_add)
        self.frame_25.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.frame_33 = QtWidgets.QFrame(self.frame_25)
        self.frame_33.setGeometry(QtCore.QRect(30, 1, 251, 49))
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_38 = QtWidgets.QFrame(self.frame_33)
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.add_fail = QtWidgets.QLabel(self.frame_38)
        self.add_fail.setGeometry(QtCore.QRect(170, 9, 52, 16))
        self.add_fail.setStyleSheet("color: rgb(255, 0, 0);")
        self.add_fail.setObjectName("add_fail")
        self.add_success = QtWidgets.QLabel(self.frame_38)
        self.add_success.setGeometry(QtCore.QRect(77, 9, 69, 16))
        self.add_success.setStyleSheet("color: rgb(60, 170, 10);")
        self.add_success.setObjectName("add_success")
        self.add_tong = QtWidgets.QLabel(self.frame_38)
        self.add_tong.setGeometry(QtCore.QRect(9, 9, 37, 16))
        self.add_tong.setStyleSheet("color: rgb(0, 85, 255);")
        self.add_tong.setObjectName("add_tong")
        self.horizontalLayout_9.addWidget(self.frame_38)
        self.line = QtWidgets.QFrame(self.frame_25)
        self.line.setGeometry(QtCore.QRect(0, 0, 800, 1))
        self.line.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.plain_add = QtWidgets.QPlainTextEdit(self.frame_25)
        self.plain_add.setGeometry(QtCore.QRect(30, 70, 741, 431))
        self.plain_add.setStyleSheet("QPlainTextEdit#plain_add{\n"
"color: rgb(77, 82, 120);\n"
"border-radius:5px;\n"
"background-color: rgb(226, 226, 226);\n"
"padding: 10px;\n"
"}\n"
"QPlainTextEdit#plain_add:hover{\n"
"color: rgb(77, 82, 120);\n"
"border-radius:5px;\n"
"border:1px solid #4d5278;\n"
"    background-color: rgb(226, 226, 226);\n"
"}")
        self.plain_add.setObjectName("plain_add")
        self.frame_34 = QtWidgets.QFrame(self.frame_25)
        self.frame_34.setGeometry(QtCore.QRect(280, 10, 271, 36))
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.add_fail_2 = QtWidgets.QLabel(self.frame_34)
        self.add_fail_2.setStyleSheet("")
        self.add_fail_2.setObjectName("add_fail_2")
        self.horizontalLayout_17.addWidget(self.add_fail_2)
        self.comboBox = QtWidgets.QComboBox(self.frame_34)
        self.comboBox.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius: 4px;\n"
"padding-left: 10px;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_17.addWidget(self.comboBox)
        self.verticalLayout_55.addWidget(self.frame_25)
        self.stackedWidget_setting.addWidget(self.page_add)
        self.page_show = QtWidgets.QWidget()
        self.page_show.setObjectName("page_show")
        self.frame_30 = QtWidgets.QFrame(self.page_show)
        self.frame_30.setGeometry(QtCore.QRect(0, 0, 799, 511))
        self.frame_30.setStyleSheet("QFrame {\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-top: 1px solid black;\n"
"}")
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.label_2 = QtWidgets.QLabel(self.frame_30)
        self.label_2.setGeometry(QtCore.QRect(290, 0, 141, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: red;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.box_session = QtWidgets.QCheckBox(self.frame_30)
        self.box_session.setGeometry(QtCore.QRect(30, 50, 91, 17))
        self.box_session.setObjectName("box_session")
        self.box_phonename = QtWidgets.QCheckBox(self.frame_30)
        self.box_phonename.setGeometry(QtCore.QRect(150, 50, 81, 17))
        self.box_phonename.setChecked(True)
        self.box_phonename.setObjectName("box_phonename")
        self.box_device = QtWidgets.QCheckBox(self.frame_30)
        self.box_device.setGeometry(QtCore.QRect(360, 50, 61, 17))
        self.box_device.setChecked(True)
        self.box_device.setObjectName("box_device")
        self.box_uniquetiktok = QtWidgets.QCheckBox(self.frame_30)
        self.box_uniquetiktok.setGeometry(QtCore.QRect(470, 50, 91, 17))
        self.box_uniquetiktok.setChecked(True)
        self.box_uniquetiktok.setObjectName("box_uniquetiktok")
        self.box_username = QtWidgets.QCheckBox(self.frame_30)
        self.box_username.setGeometry(QtCore.QRect(590, 50, 91, 17))
        self.box_username.setChecked(True)
        self.box_username.setObjectName("box_username")
        self.box_password = QtWidgets.QCheckBox(self.frame_30)
        self.box_password.setGeometry(QtCore.QRect(360, 80, 91, 17))
        self.box_password.setChecked(True)
        self.box_password.setObjectName("box_password")
        self.label_10 = QtWidgets.QLabel(self.frame_30)
        self.label_10.setGeometry(QtCore.QRect(270, 20, 201, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border: none;\n"
"color: rgb(148, 148, 148);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.box_timelast = QtWidgets.QCheckBox(self.frame_30)
        self.box_timelast.setGeometry(QtCore.QRect(250, 80, 91, 17))
        self.box_timelast.setChecked(True)
        self.box_timelast.setObjectName("box_timelast")
        self.box_total = QtWidgets.QCheckBox(self.frame_30)
        self.box_total.setGeometry(QtCore.QRect(700, 50, 61, 16))
        self.box_total.setChecked(True)
        self.box_total.setObjectName("box_total")
        self.box_vpn = QtWidgets.QCheckBox(self.frame_30)
        self.box_vpn.setGeometry(QtCore.QRect(150, 80, 51, 17))
        self.box_vpn.setChecked(True)
        self.box_vpn.setObjectName("box_vpn")
        self.box_hnay = QtWidgets.QCheckBox(self.frame_30)
        self.box_hnay.setGeometry(QtCore.QRect(30, 80, 71, 16))
        self.box_hnay.setChecked(True)
        self.box_hnay.setObjectName("box_hnay")
        self.box_version = QtWidgets.QCheckBox(self.frame_30)
        self.box_version.setGeometry(QtCore.QRect(250, 50, 81, 16))
        self.box_version.setChecked(True)
        self.box_version.setObjectName("box_version")
        self.box_cache = QtWidgets.QCheckBox(self.frame_30)
        self.box_cache.setGeometry(QtCore.QRect(470, 80, 91, 17))
        self.box_cache.setChecked(True)
        self.box_cache.setObjectName("box_cache")
        self.box_acc_run = QtWidgets.QCheckBox(self.frame_30)
        self.box_acc_run.setGeometry(QtCore.QRect(590, 80, 71, 17))
        self.box_acc_run.setChecked(False)
        self.box_acc_run.setObjectName("box_acc_run")
        self.box_jobday = QtWidgets.QCheckBox(self.frame_30)
        self.box_jobday.setGeometry(QtCore.QRect(700, 80, 91, 17))
        self.box_jobday.setChecked(False)
        self.box_jobday.setObjectName("box_jobday")
        self.stackedWidget_setting.addWidget(self.page_show)
        self.page_tacvu = QtWidgets.QWidget()
        self.page_tacvu.setObjectName("page_tacvu")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_tacvu)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.page_tacvu)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 95, 43))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_20.setContentsMargins(0, 0, 1, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.listWidget_history = QtWidgets.QListWidget(self.scrollAreaWidgetContents_3)
        self.listWidget_history.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.listWidget_history.setObjectName("listWidget_history")
        self.horizontalLayout_20.addWidget(self.listWidget_history)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_14.addWidget(self.scrollArea_3)
        self.stackedWidget_setting.addWidget(self.page_tacvu)
        self.verticalLayout_12.addWidget(self.stackedWidget_setting)
        self.horizontalLayout_10.addWidget(self.frame_cauhinh)
        self.verticalLayout_6.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_12.setStyleSheet("QFrame#frame_12{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.taskbar_dachon = QtWidgets.QLabel(self.frame_14)
        self.taskbar_dachon.setGeometry(QtCore.QRect(310, 0, 70, 16))
        self.taskbar_dachon.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.taskbar_dachon.setFont(font)
        self.taskbar_dachon.setStyleSheet("color: rgb(77, 82, 120);")
        self.taskbar_dachon.setObjectName("taskbar_dachon")
        self.taskbar_boiden = QtWidgets.QLabel(self.frame_14)
        self.taskbar_boiden.setGeometry(QtCore.QRect(230, 0, 70, 16))
        self.taskbar_boiden.setMinimumSize(QtCore.QSize(50, 0))
        self.taskbar_boiden.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.taskbar_boiden.setFont(font)
        self.taskbar_boiden.setStyleSheet("color: rgb(77, 82, 120);")
        self.taskbar_boiden.setObjectName("taskbar_boiden")
        self.taskbar_active = QtWidgets.QLabel(self.frame_14)
        self.taskbar_active.setGeometry(QtCore.QRect(0, 0, 100, 16))
        self.taskbar_active.setMinimumSize(QtCore.QSize(100, 13))
        self.taskbar_active.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.taskbar_active.setFont(font)
        self.taskbar_active.setStyleSheet("color: rgb(77, 82, 120);")
        self.taskbar_active.setObjectName("taskbar_active")
        self.taskbar_device = QtWidgets.QLabel(self.frame_14)
        self.taskbar_device.setGeometry(QtCore.QRect(110, 0, 111, 16))
        self.taskbar_device.setMinimumSize(QtCore.QSize(100, 0))
        self.taskbar_device.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.taskbar_device.setFont(font)
        self.taskbar_device.setStyleSheet("color: rgb(77, 82, 120);")
        self.taskbar_device.setObjectName("taskbar_device")
        self.taskbar_tatca = QtWidgets.QLabel(self.frame_14)
        self.taskbar_tatca.setGeometry(QtCore.QRect(390, 0, 70, 16))
        self.taskbar_tatca.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.taskbar_tatca.setFont(font)
        self.taskbar_tatca.setStyleSheet("color: rgb(77, 82, 120);")
        self.taskbar_tatca.setObjectName("taskbar_tatca")
        self.taskbar_xuhqua = QtWidgets.QLabel(self.frame_14)
        self.taskbar_xuhqua.setGeometry(QtCore.QRect(460, 0, 111, 16))
        self.taskbar_xuhqua.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.taskbar_xuhqua.setFont(font)
        self.taskbar_xuhqua.setStyleSheet("color: rgb(0, 170, 0);")
        self.taskbar_xuhqua.setObjectName("taskbar_xuhqua")
        self.taskbar_xunay = QtWidgets.QLabel(self.frame_14)
        self.taskbar_xunay.setGeometry(QtCore.QRect(590, 0, 111, 16))
        self.taskbar_xunay.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.taskbar_xunay.setFont(font)
        self.taskbar_xunay.setStyleSheet("color: rgb(0, 170, 0);")
        self.taskbar_xunay.setObjectName("taskbar_xunay")
        self.horizontalLayout_6.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_12)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_15.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_15.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.taskbar_version = QtWidgets.QLabel(self.frame_15)
        self.taskbar_version.setGeometry(QtCore.QRect(0, 0, 100, 20))
        self.taskbar_version.setMinimumSize(QtCore.QSize(50, 0))
        self.taskbar_version.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.taskbar_version.setFont(font)
        self.taskbar_version.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.taskbar_version.setStyleSheet("color: rgb(77, 82, 120);")
        self.taskbar_version.setAlignment(QtCore.Qt.AlignCenter)
        self.taskbar_version.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.taskbar_version.setObjectName("taskbar_version")
        self.horizontalLayout_6.addWidget(self.frame_15)
        self.verticalLayout_6.addWidget(self.frame_12)
        self.frame_12.raise_()
        self.frame_11.raise_()
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_setting.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tool cày xu trao đổi sub"))
        self.topTitleApp.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">Tool cày xu TDS</span></p></body></html>"))
        self.topVersionApp.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_menu.setText(_translate("MainWindow", "                        Menu"))
        self.btn_home.setText(_translate("MainWindow", "                Trang Chủ"))
        self.btn_batdau.setText(_translate("MainWindow", "                    Bắt đầu"))
        self.btn_dunglai.setText(_translate("MainWindow", "                Tạm dừng"))
        self.btn_history.setText(_translate("MainWindow", "                    Lịch sử"))
        self.btn_cauhinh.setText(_translate("MainWindow", "                 Cấu hình"))
        self.btn_add_account.setText(_translate("MainWindow", "                Tài khoản"))
        self.btn_show.setText(_translate("MainWindow", "                  Hiển thị"))
        self.btn_update.setText(_translate("MainWindow", "                Cập nhật"))
        self.btn_setting.setText(_translate("MainWindow", "                      Cài đặt"))
        self.tablewidget_page.setSortingEnabled(False)
        self.btn_reset.setText(_translate("MainWindow", "Mặc định"))
        self.btn_savecmd.setText(_translate("MainWindow", "Lưu cấu hình"))
        self.label.setText(_translate("MainWindow", "1. Phương thức lấy gmail"))
        self.radioTaphoa.setText(_translate("MainWindow", "Api Taphoammo"))
        self.radioFile.setText(_translate("MainWindow", "File"))
        self.token_taphoa.setPlaceholderText(_translate("MainWindow", "Nhập token mua hàng tạp hóa"))
        self.token_shop.setPlaceholderText(_translate("MainWindow", "Token gian hàng tạp hóa"))
        self.textGmail.setPlaceholderText(_translate("MainWindow", "Nhập list gmail, mỗi gmail 1 dòng"))
        self.label_3.setText(_translate("MainWindow", "2. Captcha"))
        self.key_captcha.setPlaceholderText(_translate("MainWindow", "Nhập api key 1captcha"))
        self.label_7.setText(_translate("MainWindow", "3. Path image"))
        self.path_image.setPlaceholderText(_translate("MainWindow", "Nhập đường dẫn ảnh"))
        self.label_8.setText(_translate("MainWindow", "4. Cấu hình chạy tool"))
        self.label_9.setText(_translate("MainWindow", "Nghỉ"))
        self.label_11.setText(_translate("MainWindow", "Giây khi chạy được "))
        self.label_12.setText(_translate("MainWindow", "Acc"))
        self.label_13.setText(_translate("MainWindow", "Start time"))
        self.label_14.setText(_translate("MainWindow", "End time"))
        self.label_5.setText(_translate("MainWindow", "Delay min"))
        self.label_6.setText(_translate("MainWindow", "Delay max"))
        self.label_15.setText(_translate("MainWindow", "Thay tài khoản tds khi đủ"))
        self.label_16.setText(_translate("MainWindow", "Xu"))
        self.limitXu.setText(_translate("MainWindow", "10000000"))
        self.add_fail.setText(_translate("MainWindow", "Thất bại: 0"))
        self.add_success.setText(_translate("MainWindow", "Thành công: 0"))
        self.add_tong.setText(_translate("MainWindow", "Tổng: 0"))
        self.plain_add.setPlaceholderText(_translate("MainWindow", "Nhập tài khoản cần thêm theo định dạng device|user|pass"))
        self.add_fail_2.setText(_translate("MainWindow", "Định dạng"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Device | Username | Password"))
        self.label_2.setText(_translate("MainWindow", "Cấu hình hiển thị"))
        self.box_session.setText(_translate("MainWindow", "Session máy"))
        self.box_phonename.setText(_translate("MainWindow", "Tên máy"))
        self.box_device.setText(_translate("MainWindow", "Device"))
        self.box_uniquetiktok.setText(_translate("MainWindow", "Tiktok_unique"))
        self.box_username.setText(_translate("MainWindow", "Username"))
        self.box_password.setText(_translate("MainWindow", "Password"))
        self.label_10.setText(_translate("MainWindow", "Vui lòng chọn những cột cần hiển thị"))
        self.box_timelast.setText(_translate("MainWindow", "Lần chạy cuối"))
        self.box_total.setText(_translate("MainWindow", "Total"))
        self.box_vpn.setText(_translate("MainWindow", "VPN"))
        self.box_hnay.setText(_translate("MainWindow", "Hôm nay"))
        self.box_version.setText(_translate("MainWindow", "Version"))
        self.box_cache.setText(_translate("MainWindow", "Cache"))
        self.box_acc_run.setText(_translate("MainWindow", "Đã chạy"))
        self.box_jobday.setText(_translate("MainWindow", "Job Hôm nay"))
        self.taskbar_dachon.setText(_translate("MainWindow", "Đã chọn: 0"))
        self.taskbar_boiden.setText(_translate("MainWindow", "Bôi đen: 0"))
        self.taskbar_active.setText(_translate("MainWindow", "Trạng thái: "))
        self.taskbar_device.setText(_translate("MainWindow", "Thiết bị: "))
        self.taskbar_tatca.setText(_translate("MainWindow", "Tất cả: 0"))
        self.taskbar_xuhqua.setText(_translate("MainWindow", "Hôm qua: 0"))
        self.taskbar_xunay.setText(_translate("MainWindow", "Hôm nay: 0"))
        self.taskbar_version.setText(_translate("MainWindow", "1.0.0"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
